# Generated by Django 4.2.20 on 2025-03-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_case_dna_n_coverage_alter_case_dna_t_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.CharField(blank=True, max_length=255, verbose_name='Project Lead'),
        ),
    ]
