# Generated by Django 4.2.20 on 2025-03-24 22:50

from django.db import migrations

def format_project_leads(apps, schema_editor):
    """
    Format all project leads to ensure consistency:
    - Trim whitespace
    - Capitalize properly
    """
    Project = apps.get_model('core', 'Project')
    for project in Project.objects.all():
        if project.project_lead:
            # Trim whitespace and capitalize properly
            project.project_lead = project.project_lead.strip().title()
            project.save()

def reverse_migration(apps, schema_editor):
    """
    No reverse migration needed
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_project_lead'),
    ]

    operations = [
        migrations.RunPython(format_project_leads, reverse_migration),
    ]
