# Generated by Django 4.2.20 on 2025-03-24 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_format_project_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Project Lead',
                'verbose_name_plural': 'Project Leads',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_lead_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectlead', verbose_name='Project Lead Object'),
        ),
    ]
