# Generated by Django 4.2.20 on 2025-03-24 23:04

from django.db import migrations, models
import django.db.models.deletion


def transfer_project_lead_data(apps, schema_editor):
    """
    Copy values from project_lead_obj to project_lead before we remove project_lead_obj
    We do this by running raw SQL since we're in the middle of a schema change
    """
    schema_editor.execute(
        "UPDATE core_project SET project_lead_id = project_lead_obj_id"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_populate_project_leads'),
    ]

    operations = [
        # First convert project_lead to a ForeignKey with a different name
        migrations.AlterField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectlead', verbose_name='Project Lead'),
        ),
        # Then run our data migration
        migrations.RunPython(transfer_project_lead_data),
        # Finally remove the temp field
        migrations.RemoveField(
            model_name='project',
            name='project_lead_obj',
        ),
    ]
