# Generated by Django 4.2.20 on 2025-03-24 23:04

from django.db import migrations

def copy_project_lead_values(apps, schema_editor):
    """
    Copy values from project_lead_obj to project_lead after the field type has changed
    """
    # This migration runs after project_lead has been changed to ForeignKey
    # and project_lead_obj has been removed, so we don't need to do anything here.
    # The values were already copied in the previous schema migration.
    pass

def reverse_migration(apps, schema_editor):
    """
    No reverse migration possible
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_replace_project_lead_field'),
    ]

    operations = [
        migrations.RunPython(copy_project_lead_values, reverse_migration),
    ]
