# Generated by Django 4.2.20 on 2025-06-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_migrate_project_lead_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('library_prepped', 'Library Prepped'), ('transferred_to_nfl', 'Transferred to NFL'), ('bioinfo_analysis', 'Bioinfo Analysis'), ('completed', 'Completed')], default='received', max_length=50),
        ),
    ]
