# Generated by Django 4.2.20 on 2025-07-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='other_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other ID'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('received', 'Received'), ('incomplete', 'Incomplete'), ('unknown', 'Unknown'), ('library_prepped', 'Library Prepped'), ('sequenced', 'Sequenced'), ('transferred_to_nfl', 'Transferred to NFL'), ('bioinfo_analysis', 'Bioinfo Analysis'), ('completed', 'Completed')], default='received', max_length=50),
        ),
    ]
