# Generated by Django 4.2.20 on 2025-07-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_groups'),
        ('core', '0015_update_tier_b_criteria_with_high_dna_no_rna'),
    ]

    operations = [
    ]
