# Generated by Django 5.1.3 on 2025-07-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20250716_1624'),
        ('core', '0016_update_tier_a_rna_criteria_80m'),
    ]

    operations = [
    ]
