# Generated by Django 4.2.20 on 2025-01-27 16:53

from django.db import migrations


def recalculate_tiers_corrected_logic(apps, schema_editor):
    """Recalculate tiers for all cases with corrected logic for RNA < 80M cases."""
    Case = apps.get_model('core', 'Case')
    
    def calculate_corrected_tier(case):
        """Calculate tier with corrected logic including RNA < 80M cases."""
        # Return FAIL if DNA coverage values are missing or below thresholds
        if case.dna_t_coverage is None or case.dna_n_coverage is None:
            return 'FAIL'
            
        # Tier FAIL: DNA(T) < 30X OR DNA(N) < 30X
        if case.dna_t_coverage < 30 or case.dna_n_coverage < 30:
            return 'FAIL'
        
        # Tier A: DNA(T) >= 80X, DNA(N) >= 30X, RNA >= 80M reads
        if (case.dna_t_coverage >= 80 and case.dna_n_coverage >= 30 and 
            case.rna_coverage is not None and case.rna_coverage >= 80):
            return 'A'
        
        # Tier B: Trois cas possibles
        # 1. 30X <= DNA(T) <= 80X, DNA(N) >= 30X, tout ce qui concerne RNA
        # 2. DNA(T) >= 80X, DNA(N) >= 30X, pas de valeur de RNA
        # 3. DNA(T) >= 80X, DNA(N) >= 30X, RNA < 80M (pas assez pour Tier A)
        if ((30 <= case.dna_t_coverage <= 80 and case.dna_n_coverage >= 30) or 
            (case.dna_t_coverage >= 80 and case.dna_n_coverage >= 30 and case.rna_coverage is None) or
            (case.dna_t_coverage >= 80 and case.dna_n_coverage >= 30 and case.rna_coverage is not None and case.rna_coverage < 80)):
            return 'B'
        
        # Default to FAIL for any other case
        return 'FAIL'
    
    # Get all cases and recalculate their tiers
    cases_to_update = []
    for case in Case.objects.all():
        old_tier = case.tier
        new_tier = calculate_corrected_tier(case)
        if old_tier != new_tier:
            case.tier = new_tier
            cases_to_update.append(case)
    
    # Bulk update to improve performance
    if cases_to_update:
        Case.objects.bulk_update(cases_to_update, ['tier'])
        print(f"Updated {len(cases_to_update)} cases with corrected tier logic (RNA < 80M cases)")
    else:
        print("No cases needed updating with corrected tier logic")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20250721_1548'),
    ]

    operations = [
        migrations.RunPython(recalculate_tiers_corrected_logic),
    ]
