# Generated by Django 5.1.3 on 2026-08-13 13:27

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20250721_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='case',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Deleted at'),
        ),
    ]
