# Generated by Django 5.1.3 on 2026-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_acc_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'base_manager_name': 'all_objects', 'ordering': ['-is_priority', 'acc_number', 'name']},
        ),
        migrations.AddField(
            model_name='case',
            name='is_priority',
            field=models.BooleanField(db_index=True, default=False, help_text='Flags a patient whose prognosis makes this urgent.', verbose_name='Priority case'),
        ),
        migrations.AddField(
            model_name='project',
            name='kind',
            field=models.CharField(choices=[('research', 'Research project'), ('referred', 'Referred cases')], default='research', max_length=16, verbose_name='Project type'),
        ),
    ]
