# Generated by Django 5.1.3 on 2026-08-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_referred_cases_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('sent_to_sequencing', 'Sent to Sequencing Center'), ('received', 'Received'), ('qc_complete', 'QC complete'), ('library_complete', 'Library complete'), ('iseq_finished', 'iSeq finished'), ('sequencing_complete', 'Sequencing Complete'), ('transferred_to_cair', 'Transferred to CAIR'), ('analyzing', 'Analyzing'), ('analysis_complete', 'Analysis complete'), ('unknown_legacy', 'Unknown (pre-V2)')], db_index=True, default='case_created', editable=False, max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_type', models.CharField(choices=[('normal_dna', 'Normal (DNA)'), ('tumour_dna', 'Tumour (DNA)'), ('tumour_rna', 'Tumour (RNA)')], max_length=16, verbose_name='Specimen type')),
                ('status', models.CharField(choices=[('case_created', 'Case Created'), ('sent_to_sequencing', 'Sent to Sequencing Center'), ('received', 'Received'), ('qc_complete', 'QC complete'), ('library_complete', 'Library complete'), ('iseq_finished', 'iSeq finished'), ('sequencing_complete', 'Sequencing Complete'), ('transferred_to_cair', 'Transferred to CAIR'), ('analyzing', 'Analyzing'), ('analysis_complete', 'Analysis complete'), ('unknown_legacy', 'Unknown (pre-V2)')], db_index=True, default='case_created', max_length=32, verbose_name='Status')),
                ('coverage', models.FloatField(blank=True, help_text='X for DNA, million reads for RNA.', null=True, verbose_name='Coverage')),
                ('external_id', models.CharField(blank=True, help_text='Identifier issued by the sequencing centre, if any.', max_length=255, null=True, verbose_name='Sequencing centre ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='core.case')),
            ],
            options={
                'verbose_name': 'Specimen',
                'verbose_name_plural': 'Specimens',
                'constraints': [models.UniqueConstraint(fields=('case', 'specimen_type'), name='uniq_specimen_per_case')],
            },
        ),
    ]
