# Generated by Django 5.1.3 on 2026-08-25 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_backfill_specimens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status_set', models.CharField(choices=[('case_created', 'Case Created'), ('sent_to_sequencing', 'Sent to Sequencing Center'), ('received', 'Received'), ('qc_complete', 'QC complete'), ('library_complete', 'Library complete'), ('iseq_finished', 'iSeq finished'), ('sequencing_complete', 'Sequencing Complete'), ('transferred_to_cair', 'Transferred to CAIR'), ('analyzing', 'Analyzing'), ('analysis_complete', 'Analysis complete'), ('unknown_legacy', 'Unknown (pre-V2)')], max_length=32)),
                ('applied_to', models.CharField(default='all', max_length=16)),
                ('case_count', models.PositiveIntegerField(default=0)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_operations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_operations', to='core.project')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_undos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch operation',
                'verbose_name_plural': 'Batch operations',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecimenStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.batchoperation')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.specimen')),
            ],
            options={
                'verbose_name': 'Specimen status change',
                'verbose_name_plural': 'Specimen status changes',
            },
        ),
    ]
