# Generated by Django 5.1.3 on 2026-08-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_batch_operations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='case',
            name='uniq_active_acc_number',
        ),
        migrations.AddField(
            model_name='case',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Attempt'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='A later attempt replaced this one.', verbose_name='Superseded'),
        ),
        migrations.AddField(
            model_name='case',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.case', verbose_name='Superseded by'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_archived', False)), fields=('acc_number',), name='uniq_active_acc_number', violation_error_message='This ACC identifier is already used by another case.'),
        ),
    ]
