# Generated by Django 5.1.3 on 2026-08-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_case_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='preservation',
            field=models.CharField(choices=[('ff', 'Fresh frozen (FF)'), ('ffpe', 'FFPE'), ('other', 'Other'), ('unknown', 'Not recorded')], default='unknown', max_length=16, verbose_name='Preservation'),
        ),
    ]
