# Generated by Django 5.1.3 on 2026-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='report_returned',
            field=models.BooleanField(db_index=True, default=False, help_text='The report has been returned to the patient.', verbose_name='Report returned'),
        ),
        migrations.AddField(
            model_name='case',
            name='report_returned_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Report returned on'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='consented_generation_all',
            field=models.BooleanField(db_index=True, default=False, help_text='Has this sample been consented to Generation All?', verbose_name='Consented to Generation All'),
        ),
    ]
